# Generated by Django 5.2 on 2025-11-18 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="url",
        ),
    ]
