# Generated by Django 5.2 on 2025-11-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_remove_form_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
