# Generated by Django 5.2.1 on 2025-05-15 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
