# Generated by Django 5.2 on 2025-11-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_form_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="notify_ever",
            field=models.IntegerField(default=7),
        ),
    ]
