# Generated by Django 5.2 on 2025-05-21 22:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counties", "0003_alter_county_options"),
        ("forms", "0003_form_date_uploaded_form_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="county",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="counties.county",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="form",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="forms/completed",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx"]
                    )
                ],
            ),
        ),
    ]
