# Generated by Django 5.2 on 2025-11-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_form_notify_ever"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form",
            old_name="notify_ever",
            new_name="notify_every",
        ),
    ]
