# Generated by Django 5.2 on 2025-11-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_rename_notify_ever_form_notify_every"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="next_notify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
