# Generated by Django 5.2 on 2026-01-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counties", "0001_initial"),
        ("forms", "0006_form_next_notify_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="counties",
            field=models.ManyToManyField(
                blank=True,
                related_name="forms",
                through="forms.CountyForm",
                to="counties.county",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="countyform", unique_together={("county", "form")},
        ),
    ]
