# Generated by Django 5.2 on 2026-01-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_form_counties_alter_countyform_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="countyform",
            name="completed_file_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
