"""
Django settings for Civisight project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

MADE AUTHENTICATION MORE RELAXED (Daksh)
"""
import os
from urllib.parse import urlparse
from pathlib import Path
from dotenv import load_dotenv
from supabase import create_client



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-obzlt8+y5t+o1^!%8z_&j*#c30(4ee-gg&3u(%$f7b#z8p!2za'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'accounts',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'counties',
    'states',
    'forms',
    'storages'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://localhost:3002",
    "http://127.0.0.1:3002",
    "https://civisight-nine.vercel.app"
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://civisight-nine.vercel.app'
]

ALLOWED_HOSTS = [
    'civisight.onrender.com',
    'localhost'
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'Civisight.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Civisight.wsgi.application'

DATABASE_URL = os.getenv('DATABASE_URL')

RESULT = urlparse(DATABASE_URL)

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': RESULT.path.decode('utf-8').lstrip('/') if isinstance(RESULT.path, bytes) else RESULT.path.lstrip('/'),
        'USER': RESULT.username,
        'PASSWORD': RESULT.password,
        'HOST': RESULT.hostname,
        'PORT': RESULT.port,
        'OPTIONS': {'sslmode': 'require'}
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Directory where `collectstatic` will collect static files for production
# Use a folder at the project root named `staticfiles`.
STATIC_ROOT = BASE_DIR / 'staticfiles'

AUTH_USER_MODEL = 'accounts.User'

STORAGES = {
    # keep staticfiles local (or point this to S3 if you prefer)
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    # default (media) storage → Supabase
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            # server-side credentials (from your Supabase project settings)
            "access_key": os.getenv("SUPABASE_S3_ACCESS_KEY_ID"),
            "secret_key": os.getenv("SUPABASE_S3_SECRET_ACCESS_KEY"),
            # the bucket you created in Supabase Storage
            "bucket_name": os.getenv("SUPABASE_S3_BUCKET_NAME"),
            # your project’s region (e.g. "us-east-1")
            "region_name": os.getenv("SUPABASE_S3_REGION_NAME"),
            # S3 endpoint for Supabase
            "endpoint_url": os.getenv("SUPABASE_S3_ENDPOINT_URL"),
            # Ensure compatibility with Supabase S3 API
            "signature_version": "s3v4",
            "addressing_style": "path",
            "use_ssl": True,
        }
    }
}

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_API_KEY = os.environ["SUPABASE_API_KEY"]
SUPABASE_SERVICE_KEY = os.environ.get("SUPABASE_SERVICE_KEY", SUPABASE_API_KEY)
SUPABASE_JWKS_URL = os.environ["SUPABASE_JWKS_URL"]
SUPABASE_JWT_SECRET = os.environ["SUPABASE_JWT_SECRET"]

# Use the service key on the server for Storage writes (anon key may lack insert permissions)
# Django only exposes UPPERCASE attributes via django.conf.settings, so set an uppercase alias too.
SUPABASE_CLIENT = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)
# Back-compat alias if referenced elsewhere in code
supabase = SUPABASE_CLIENT

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "accounts.backends.SupabaseBackend",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
         "rest_framework.authentication.SessionAuthentication",
    #     # If you have JWT or token auth, add it here
    ],
    "DEFAULT_PERMISSION_CLASSES": [
         "rest_framework.permissions.IsAuthenticatedOrReadOnly",\
         "rest_framework.permissions.IsAuthenticated",
    ],
}


# TODO: add email backend and change to SMTP instead of console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# (Celery removed) Use the management command `send_reminders` for scheduled reminders.

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
# EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Cookie configuration
# You can override the cookie domain by setting COOKIE_DOMAIN in the environment.
# By default it is set to the backend host so cookies are scoped to that domain.
COOKIE_DOMAIN = os.getenv('COOKIE_DOMAIN', 'civisight.onrender.com')
if COOKIE_DOMAIN:
    if not COOKIE_DOMAIN.startswith('.'):
        COOKIE_DOMAIN = f'.{COOKIE_DOMAIN}'
    SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN
    CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN

# In production we require Secure cookies and explicit SameSite for cross-site use.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # If your frontend is hosted on a different root domain you may need 'None'
    SESSION_COOKIE_SAMESITE = None
    CSRF_COOKIE_SAMESITE = None
else:
    # Local development: allow cookies over HTTP and use Lax for safety.
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_HTTPONLY = False