# Generated by Django 5.2 on 2025-05-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_stateofficial"),
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="countyofficial",
            name="forms",
            field=models.ManyToManyField(to="forms.form"),
        ),
    ]
