# Generated by Django 5.2.1 on 2025-05-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_countyofficial_forms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countyofficial',
            options={'verbose_name': 'County Official', 'verbose_name_plural': 'County Officials'},
        ),
        migrations.AlterModelOptions(
            name='stateofficial',
            options={'verbose_name': 'State Official', 'verbose_name_plural': 'State Officials'},
        ),
    ]
