# Generated by Django 5.2 on 2025-05-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_countyofficial_options_and_more"),
        ("forms", "0003_form_date_uploaded_form_is_completed"),
    ]

    operations = [
        migrations.RemoveField(model_name="countyofficial", name="forms",),
        migrations.AddField(
            model_name="countyofficial",
            name="completed_forms",
            field=models.ManyToManyField(
                related_name="countyofficial_complete", to="forms.form"
            ),
        ),
        migrations.AddField(
            model_name="countyofficial",
            name="incomplete_forms",
            field=models.ManyToManyField(
                related_name="countyofficial_incomplete", to="forms.form"
            ),
        ),
        migrations.AlterField(
            model_name="user", name="email", field=models.EmailField(max_length=254),
        ),
    ]
