# Generated by Django 5.2 on 2025-05-13 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counties", "0001_initial"),
        ("states", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="county",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counties",
                to="states.state",
            ),
        ),
    ]
