# Generated by Django 5.2.1 on 2025-05-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0002_county_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
    ]
