# Generated by Django 5.2 on 2025-06-19 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0003_alter_county_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='county',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='county',
            name='task_count',
            field=models.IntegerField(default=0),
        ),
    ]
